### PR TITLE
clickhouse: new experimental storage type

### PR DESCRIPTION
**Pull request by narqo**
The PR adds a new _experimental_ storage type, based on [ClickHouse database][1]. The storage parses pprof data and stores individual samples in ClickHouse.

A new command line flag `--storage-type=<type>`, that defines profefe's storage type:

```
$ profefe \
  -addr=localhost:10100 \
  -storage-type=clickhouse \
  -clickhouse.dsn='tcp://127.0.0.1:9000?database=profefe'
```

TODO:

- [x] provide persistent database schema
- [x] calculate storage requirements
- [x] set up integration tests from `storage/clickhouse` to run on CI

## Implementation details

In the current implementation, there is no way to restore the pprof from the DB. That is, `Storage.ListProfiles` is not supported. The storage is intended to be used with analytical subsystems that work directly with ClickHouse.

The storage only supports pprof profiles, i.e. `type=trace` doesn't work — storage returns "unsupported profile type" error.

The recommended SQL schema is in `pkg/storage/clickhouse/schema/profefe.sql`.

<details>
<summary>Outdated details</summary>

In this implementation, storage uses the following DB schema (_not really, see the discussion below_):

```sql
CREATE TABLE IF NOT EXISTS pprof_profiles (
	profile_key FixedString(12),
	profile_type Enum8(
		'cpu' = 1,
		'heap' = 2,
		'block' = 3,
		'mutex' = 4,
		'goroutine' = 5,
		'threadcreate' = 6,
		'other' = 100
	),
	external_id String,
	service_name LowCardinality(String),
	created_at DateTime,
	labels Nested (
		key LowCardinality(String),
		value String
	)
) engine=Memory

CREATE TABLE IF NOT EXISTS pprof_samples (
	profile_key FixedString(12),
	digest UInt64,
	locations Nested (
		func_name LowCardinality(String),
		file_name LowCardinality(String),
		lineno UInt16
	),
	values Array(UInt64),
	labels Nested (
		key String,
		value String
	)
) engine=Memory
```

Note, `engine=Memory` is obviously not supposed to be used in production.

</details>

[1]: https://clickhouse.tech/

### CODE REVIEW

**Comment by Slach** [comment]
wow ;) great feature!
it make opportunity to visualize execution process via Grafana Dashboards for any time period!

**Comment by Slach** [comment]
Really great feature!

Some suggestions about table schema:

we can use Engine Buffer() + create separate table with Engine MegreTree() for production usage
also we can create MergeTree with TTL to automatically clear old values from MergeTree table
also we can use cluster() function for query over all nodes in cluster without Zookeeper and replications, also we can deploy Clickhouse via clickhouse-operator for each node
and can use clickhouse-operator + kube-profefe together

I can't figure out how we can properly make full stack trace and prepare data for flamegraph from flat nested array `locations` and flat array `values`

what mean each element in `pprof_samples.values`? and what mean `digest`  field?

for internal clickhouse sampling CPU / Memory profiler
following structure and query was used
```
SELECT 
	profile_key,
	count() AS samples, 
	arrayStringConcat(arrayReverse(arrayMap(x -> concat( demangle(addressToSymbol(x)), '#', addressToLine(x) ), trace)), ';') AS stack
FROM system.trace_log
GROUP BY query_id, trace

``` 
it assume each row in `system.trace_log` it's a one separate stack

i try something like
```
SELECT
	arrayStringConcat(
	    arrayReverse(
	        arrayMap(
	            (func_name, file_name, lineno) -> concat( file_name, ':', toString(lineno), '#', func_name ),
                locations.func_name, locations.file_name, locations.lineno
            )
        ), ';') AS stack,
    sum(arraySum(values)) AS samples
FROM default.pprof_samples
GROUP BY stack;
```
but  i not sure about sum(arraySum(values))

also for properly aggregation during subset of profiles
we should use something like
```
SELECT ...
FROM
 WHERE profile_key IN (
   SELECT profile_key WHERE service_name = XXX 
 )
```

**Comment by narqo** [comment]
@Slach thank you for the engine suggestions. ClickHouse's engines are the part of ClickHouse I'm currently familiarizing myself with. Indeed MergeTree with TTL sounds like a proper choice for the production deployment.

---

_Sorry for the wall of text, but hope it will help with the understanding of what is happening here._

The data model of a pprof profile (refer to [the description of profile.proto in pprof repository][1]):

For what was implemented in this PR, I treat a parsed profile as described below (_described in terms of Go structs for simplicity, the actual code is different_)

```go
type Profile struct {
  TimeNanos int64
  Sample    []Sample
}

type Sample struct {
  Value    []int64
  Location []Location
  Label    []Label
}

type Location struct {
  FuncName string
  FileName string
  Line     int64
}

type Label struct {
  Key string
  Value string
}
```

A profile consists of a set of samples. Each sample represents:
- values measured during profile 
- associated call stack as a list of locations
- an optional set of labels, associated with the call stack (set via `runtime/pprof.Do()` in Go).

The list of values in `Profile.Sample.Value` contains measurements collected for a profile type. That is, for a HEAP profile the list contains corresponding values for count and size of allocated objects (_alloc_objects, _alloc_space_), and count and size of in-used objects (_inuse_objects_, _inuse_space_); for a CPU profile — the number of samples and CPU time; for a goroutine profile — the number of goroutines; for custom profile types it can be anything.

The list of locations `Profile.Samples.Location` is the sample's call stack. For this implementation, we don't store the information about inlined functions.

To answer your questions:

> what mean each element in `pprof_samples.values`?

For the database schema, `pprof_samples.values` is literally the values of the sample, in the same order, they were present in pprof file.

pprof describes that, by default, the last value should be used. For example, for CPU profiles, CPU time in nanoseconds is `values[-1]`. In `go tool pprof` you pass `-sample_index=` to specify what measurements should be used.

> and what mean `pprof_samples.digest` field?

Digest (or fingerprint) can be used to match the same samples from different profiles when merging or diffing profiles.

Some examples

- mimicking `pprof top` (for a single profile)

```sql
SELECT flat, cum, func
FROM (
    SELECT sum(values[-1])        AS flat,
        `locations.func_name`[1] AS func
    FROM pprof_samples
    GROUP BY func
) t1
join (
    SELECT sum(values[-1])     AS cum,
        `locations.func_name` AS func
    FROM pprof_samples
        ARRAY JOIN `locations.func_name`
    GROUP BY func
) t2 USING func
ORDER BY flat DESC;
```

- merge profiles

```sql
SELECT
	sumForEach(values) AS values,
	any(`locations.func_name`) AS funcs
FROM pprof_samples
GROUP BY digest
```

- diff profiles

```sql
SELECT
    groupArray(values[-1]) AS cpu_vals,
    arrayEnumerate(cpu_vals) AS indexes,
    arrayMap(i -> cpu_vals[i] - cpu_vals[i-1], indexes) AS diffs,
    any(funcs) as funcs
FROM (
    SELECT digest, values, `locations.func_name` AS funcs
    FROM pprof_samples
    ORDER BY profile_key
)
GROUP BY digest;
```

[1]: https://github.com/google/pprof/tree/c6e0a841f49a24fb25b923df737d875cf12b6a96/proto

**Comment by Slach** [comment]
yep, I found these SQL queries in comments ;)
I will wait when you merge this functionality in master
also I think I need demo project where I can use `clickhouse-operator` + `kube-profefe` and try to add Grafana Dashboard for collecting memory / cpu / go-routines profile

**Comment by narqo** [comment]
Did some testing base on `MergeTree` engine:

<details>
<summary><code>schema/profefe.sql</code></summary>

```sql
CREATE TABLE pprof_profiles (
    profile_key FixedString(12),
    profile_type Enum8(
        'cpu' = 1,
        'heap' = 2,
        'block' = 3,
        'mutex' = 4,
        'goroutine' = 5,
        'threadcreate' = 6,
        'other' = 100
    ),
    external_id String,
    service_name LowCardinality(String),
    created_at DateTime,
    labels Nested (
        key LowCardinality(String),
        value String
    )
)
ENGINE=MergeTree()
PARTITION BY (toYYYYMM(created_at), service_name)
ORDER BY (service_name, profile_type, created_at);

CREATE TABLE pprof_samples (
    profile_key FixedString(12),
    fingerprint UInt64,
    locations Nested (
        func_name LowCardinality(String),
        file_name LowCardinality(String),
        lineno UInt16
    ),
    values Array(UInt64),
    values_type Array(LowCardinality(String)),
    values_unit Array(LowCardinality(String)),
    labels Nested (
        key String,
        value String
    )
)
ENGINE=MergeTree()
ORDER BY (profile_key, fingerprint);
```

</details>

Have imported a historical data from quite large heap profiles from one of production instances

```
› ls -1 ~/pprof/profefe-testdata-2020-03/a_server-heap-10-*Z-backend-1.prof | wc -l
      35

› du -d0 -h ~/pprof/profefe-testdata-2020-03/a_server-heap-10-*Z-backend-1.prof
1.1M	/Users/varankinv/pprof/profefe-testdata-2020-03/adjust_server-heap-10-0006Z-backend-1.prof
...

› ./scripts/pprof_import.sh --service a_server --label host=backend-1 --label dc=fra --type heap -- ~/pprof/profefe-testdata-2020-03/a_server-heap-10-*Z-backend-1.prof
uploading /Users/varankinv/pprof/profefe-testdata-2020-03/a_server-heap-10-0006Z-backend-1.prof...OK
...
```

Number of sampels per profiles (max):

```sql
SELECT
    count(),
    xxHash32(profile_key) AS pk
FROM pprof_samples
GROUP BY pk
ORDER BY count() DESC
LIMIT 1

┌─count()─┬─────────pk─┐
│   50608 │ 3786135997 │
└─────────┴────────────┘
```

Storage space required

```sql
SELECT
    name,
    formatReadableSize(sum(data_compressed_bytes)) AS compressed,
    formatReadableSize(sum(data_uncompressed_bytes)) AS uncompressed,
    (sum(data_compressed_bytes) * 100) / sum(data_uncompressed_bytes) AS compress_ratio
FROM system.columns
WHERE table = 'pprof_samples'
GROUP BY name
    WITH TOTALS
ORDER BY sum(data_compressed_bytes) ASC

┌─name────────────────┬─compressed─┬─uncompressed─┬──────compress_ratio─┐
│ labels.key          │ 61.87 KiB  │ 13.54 MiB    │  0.4461355807121269 │
│ labels.value        │ 61.87 KiB  │ 13.54 MiB    │  0.4461355807121269 │
│ profile_key         │ 91.85 KiB  │ 20.31 MiB    │ 0.44152787206015043 │
│ values_unit         │ 97.00 KiB  │ 20.32 MiB    │  0.4661450128913207 │
│ values_type         │ 97.51 KiB  │ 20.32 MiB    │ 0.46860157330623475 │
│ fingerprint         │ 13.60 MiB  │ 13.54 MiB    │  100.39641316992515 │
│ values              │ 16.62 MiB  │ 67.71 MiB    │  24.540520138245345 │
│ locations.file_name │ 17.11 MiB  │ 64.10 MiB    │  26.691578000581224 │
│ locations.func_name │ 17.70 MiB  │ 64.36 MiB    │  27.501017698696764 │
│ locations.lineno    │ 19.49 MiB  │ 64.03 MiB    │  30.441356054024965 │
└─────────────────────┴────────────┴──────────────┴─────────────────────┘

Extremes:
┌─name─┬─compressed─┬─uncompressed─┬─────compress_ratio─┐
│      │ 84.92 MiB  │ 361.80 MiB   │ 23.470943255834747 │
└──────┴────────────┴──────────────┴────────────────────┘
```

If I read it correctly, storing raw profiles in ClickHouse requires 3x more space than required for blobs of `pb.gz`. I think that's 🆗 for a prototype.

**Comment by narqo** [comment]
Another thing is that importing such large profiles takes <8s per profile. This might be too long for collector. 

From collector's own profiling, the majority of the time it spends in [`samplesWriter.insertSamples` loop](https://github.com/profefe/profefe/blob/9dd1b1a140749824a864226582cdd8685d17e6f7/pkg/storage/clickhouse/writer.go#L158), where we assemble the blocks.

This might be not a huge problem for the majority of cases. But it sounds like the same issue I saw a year ago, when collector was backed by pg :(

---

As an alternative setup, with the way how we probably would set it up internally:

1. run `profefe -storage-type=badger,kafka` 
Need to implement `kafka` storage type, to where collector will publish the meta-data about profiles stored in local badger (we can't publish pprof files to Kafka, they are too large)
2. implement `profefe-injector -storage-type=clickhouse`, who would listen to the Kafka topic, consumed meta-data, read the pprof blobs from collector (1) and wroute them to clickhouse.

**Comment by Slach** [comment]
@narqo could you share `./scripts/pprof_import.sh`?
do we insert data as one batch INSERT with CSV / TSV format?

also, I think you should use:
 `sum(data_uncompressed_bytes) / sum(data_compressed_bytes)` AS compress_ratio

what you mean, when say
> such large profiles takes <8s per profile

it's mean each profile insertion take around 8 seconds for insert to ClickHouse? hmm... 
as i see in 
https://github.com/profefe/profefe/blob/9dd1b1a140749824a864226582cdd8685d17e6f7/pkg/storage/clickhouse/writer.go#L18
you try insert each sample as separate INSERT statement

it works not good for MergeTree
you should use combination with two tables
first table Engine=Buffer()
and second table Engine=MergreTree()
and select from buffer table
look to docs https://clickhouse.yandex/docs/en/operations/table_engines/buffer/

**Comment by narqo** [comment]
> > such large profiles take <8s per profile
> it's mean each profile insertion take around 8 seconds for insert to ClickHouse?

Not precisely. 8s is what it takes for profefe to write the profile. I'm sure the bottleneck isn't directly in ClickHouse, but in the batch formation routine. 

I believe, ClickHouse's Go client handles batching per `*sql.Tx` object (_this is also what I see in CH-client's debug logging_). The relevant code is in [`(*samplesWriter) insertPprofSamples`][2]: where one loops through the samples from the profile and populate the batch (`for n, sample := range samples {···}`); next the batch is sent to the wire with `tx.Commit()`. 

I will try with `Engine=Buffer()`, thank you. Note, though, even with `engine=Memory()`, importing a profile of 50K samples takes 5-7s (_both profefe and CH run locally on my macbook_).

> could you share ./scripts/pprof_import.sh?

[This script][1] is in the repo's master branch.

[1]: https://github.com/profefe/profefe/blob/master/scripts/pprof_import.sh
[2]: https://github.com/profefe/profefe/blob/9dd1b1a140749824a864226582cdd8685d17e6f7/pkg/storage/clickhouse/writer.go#L159

**Comment by narqo** [comment]
> Another thing is that importing such large profiles takes <8s per profile. This might be too long for collector.

Apparently this wasn't 100% true. After a closer look, the majority of time was spent between encoding the data into clickhouse's wire format and sending the data over the wire. After enabling client-side compression the importing time dropped to <1s per profile 🎉 

```
$ ./BUILD/profefe -addr=localhost:10100 \
  -storage-type=clickhouse \
  -clickhouse.dsn='tcp://127.0.0.1:9000?compress=1'
```

As a side-effect, CPU usage for importing increased quite significantly, but for collector's use-case, this is acceptable.

**Comment by Slach** [comment]
> After enabling client-side compression the importing time dropped to <1s per profile
great, nice to hear it, it's sad about high CPU usage by compression, cause we can't manipulate by lz4 compression rate

**Pull request merged**
